.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel func_80000400_1000
    /* 1000 80000400 3C08800B */  lui        $t0, %hi(main_BSS_START)
    /* 1004 80000404 25088AF0 */  addiu      $t0, $t0, %lo(main_BSS_START)
    /* 1008 80000408 3C090003 */  lui        $t1, %hi(main_BSS_SIZE)
    /* 100C 8000040C 2529E080 */  addiu      $t1, $t1, %lo(main_BSS_SIZE)
  .L80000410_1010:
    /* 1010 80000410 AD000000 */  sw         $zero, 0x0($t0)
    /* 1014 80000414 AD000004 */  sw         $zero, 0x4($t0)
    /* 1018 80000418 21080008 */  addi       $t0, $t0, 0x8 /* handwritten instruction */
    /* 101C 8000041C 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1020 80000420 1520FFFB */  bnez       $t1, .L80000410_1010
    /* 1024 80000424 00000000 */   nop
    /* 1028 80000428 3C0A8000 */  lui        $t2, %hi(func_80000460_1060)
    /* 102C 8000042C 254A0460 */  addiu      $t2, $t2, %lo(func_80000460_1060)
    /* 1030 80000430 3C1D800D */  lui        $sp, %hi(gThread3Stack)
    /* 1034 80000434 01400008 */  jr         $t2
    /* 1038 80000438 27BD0300 */   addiu     $sp, $sp, %lo(gThread3Stack)
    /* 103C 8000043C 00000000 */  nop
    /* 1040 80000440 00000000 */  nop
    /* 1044 80000444 00000000 */  nop
    /* 1048 80000448 00000000 */  nop
    /* 104C 8000044C 00000000 */  nop
    /* 1050 80000450 00000000 */  nop
    /* 1054 80000454 00000000 */  nop
    /* 1058 80000458 00000000 */  nop
    /* 105C 8000045C 00000000 */  nop
.size func_80000400_1000, . - func_80000400_1000
