#ifndef _ENUMS_H_
#define _ENUMS_H_

#include "common.h"

#define SPACE_TYPES_TOTAL 16
#define SPACES_MAX 128

enum LANGUAGE {
    LANGUAGE_NONE = 0,
    LANGUAGE_JAPANESE = 1,
    LANGUAGE_ENGLISH = 2,
    LANGUAGE_FRENCH = 3,
    LANGUAGE_GERMAN = 4,
    LANGUAGE_SPANISH = 5,
    LANGUAGE_ITALIAN = 6,
    LANGUAGE_MAX
};

enum ITEMS {
    ITEM_NONE = -1,
    ITEM_MUSHROOM = 0,
    ITEM_SKELETON_KEY = 1,
    ITEM_POISON_MUSHROOM = 2,
    ITEM_REVERSE_MUSHROOM = 3,
    ITEM_CELLULAR_SHOPPER = 4,
    ITEM_WARP_BLOCK = 5,
    ITEM_PLUNDER_CHEST = 6,
    ITEM_BOWSER_PHONE = 7,
    ITEM_DUEL_GLOVE = 8,
    ITEM_LUCKY_LAMP = 9,
    ITEM_GOLDEN_MUSHROOM = 10,
    ITEM_BOO_BELL = 11,
    ITEM_BOO_REPELLENT = 12,
    ITEM_BOWSER_SUIT = 13,
    ITEM_MAGIC_LAMP = 14,
    ITEM_KOOPA_KARD = 15,
    ITEM_BARTER_BOX = 16,
    ITEM_LUCKY_CHARM = 17,
    ITEM_WACKY_WATCH = 18,
    ITEMS_END
};

enum PARTNERS {
    PARTNER_NONE = -1,
    PARTNER_KOOPA = 0,
    PARTNER_GOOMBA = 1,
    PARTNER_TOAD = 2,
    PARTNER_BOB_OMB = 3,
    PARTNER_BOO = 4,
    PARTNER_WHOMP = 5,
    PARTNER_SNIFIT = 6,
    PARTNER_PIRANHA_PLANT = 7,
    PARTNER_CHOMP = 8,
    PARTNER_THWOMP = 9,
    PARTNER_MR_BLIZZARD = 10,
    PARTNER_BABY_BOWSER = 11,
};

enum MINIGAME_TYPE {
    MINIGAME_4P,
    MINIGAME_1V3,
    MINIGAME_2V2,
    MINIGAME_ITEM,
    MINIGAME_BATTLE,
    MINIGAME_1V1
};

enum CHARACTER_IMAGES {
    CHAR_TOAD = 3,
    CHAR_BABY_BOWSER = 5,
};

enum REV_FLAGS {
    FLAG_REV = 1,
    FLAG_UNK_80 = 0x80
};

enum PlayerFlags {
    PLAYER_IS_CPU = 1,
  };

#endif //_ENUMS_H_