#ifndef _ENUMS_H_
#define _ENUMS_H_

#include "common.h"

#define SPACE_TYPES_TOTAL 16
#define SPACES_MAX 128

enum LANGUAGE {
    LANGUAGE_NONE = 0,
    LANGUAGE_JAPANESE = 1,
    LANGUAGE_ENGLISH = 2,
    LANGUAGE_FRENCH = 3,
    LANGUAGE_GERMAN = 4,
    LANGUAGE_SPANISH = 5,
    LANGUAGE_ITALIAN = 6,
    LANGUAGE_MAX
};

enum ITEMS {
    ITEM_NONE = -1,
    ITEM_MUSHROOM = 0,
    ITEM_SKELETON_KEY = 1,
    ITEM_POISON_MUSHROOM = 2,
    ITEM_REVERSE_MUSHROOM = 3,
    ITEM_CELLULAR_SHOPPER = 4,
    ITEM_WARP_BLOCK = 5,
    ITEM_PLUNDER_CHEST = 6,
    ITEM_BOWSER_PHONE = 7,
    ITEM_DUEL_GLOVE = 8,
    ITEM_LUCKY_LAMP = 9,
    ITEM_GOLDEN_MUSHROOM = 10,
    ITEM_BOO_BELL = 11,
    ITEM_BOO_REPELLENT = 12,
    ITEM_BOWSER_SUIT = 13,
    ITEM_MAGIC_LAMP = 14,
    ITEM_KOOPA_KARD = 15,
    ITEM_BARTER_BOX = 16,
    ITEM_LUCKY_CHARM = 17,
    ITEM_WACKY_WATCH = 18,
    ITEMS_END
};

enum PARTNERS {
    PARTNER_NONE = -1,
    PARTNER_KOOPA = 0,
    PARTNER_GOOMBA = 1,
    PARTNER_TOAD = 2,
    PARTNER_BOB_OMB = 3,
    PARTNER_BOO = 4,
    PARTNER_WHOMP = 5,
    PARTNER_SNIFIT = 6,
    PARTNER_PIRANHA_PLANT = 7,
    PARTNER_CHOMP = 8,
    PARTNER_THWOMP = 9,
    PARTNER_MR_BLIZZARD = 10,
    PARTNER_BABY_BOWSER = 11,
};

enum MINIGAME_TYPE {
    MINIGAME_4P,
    MINIGAME_1V3,
    MINIGAME_2V2,
    MINIGAME_ITEM,
    MINIGAME_BATTLE,
    MINIGAME_1V1
};

enum CHARCTERS {
    CHAR_MARIO = 0,
    CHAR_LUIGI = 1,
    CHAR_PEACH = 2,
    CHAR_YOSHI = 3,
    CHAR_WARIO = 4,
    CHAR_DK = 5,
    CHAR_WALUIGI = 6,
    CHAR_DAISY = 7
};

enum CHARACTER_IMAGES {
    CHAR_NONE = -1,
    CHAR_NONE2 = 0,
    CHAR_RED_KOOPA = 1,
    CHAR_GREEN_KOOPA = 2,
    CHAR_TOAD = 3,
    CHAR_BOWSER = 4,
    CHAR_BABY_BOWSER = 5,
    CHAR_GOOMBA = 6,
    CHAR_BOO = 7,
    CHAR_THWOMP = 8, //blue
    CHAR_SNUFIT = 9,
    CHAR_GAME_GUY = 10,
    CHAR_RED_BOB_OMB = 11,
    CHAR_WHOMP = 12,
    CHAR_TOAD_1 = 13,
    CHAR_BLUE_PIPE = 14,
    CHAR_PIPE_UNK = 15,
    CHAR_PIPE_UNK2 = 16,
    CHAR_PIPE_UNK3 = 17,
    CHAR_PIPE_UNK4 = 18,
    CHAR_GREEN_THING = 19,
    CHAR_YELLOW_THING = 20,
    CHAR_TUMBLE = 21,
    CHAR_MILLENIUM_STAR = 22,
    CHAR_KOOPA_GREEN = 23,
    CHAR_GOOMBA_2 = 24,
    CHAR_TOAD_2 = 25,
    CHAR_BOB_OMB = 26,
    CHAR_BOO_2 = 27,
    CHAR_WHOMP_2 = 28,
    CHAR_SNIFIT = 29,
    CHAR_PIRANHA_PLANT = 30,
    CHAR_CHAIN_CHOMP = 31,
    CHAR_THWOMP_2 = 32, //not blue?
    CHAR_MR_BLIZZARD = 33,
    CHAR_BOWSER_JR = 34,
    CHAR_MUSHROM = 35,
    CHAR_SKELETON_KEY = 36,
    CHAR_POISON_MUSHROOM = 37,
    CHAR_REVERSE_MUSHROOM = 38,
    CHAR_CELLULAR_SHOPPER = 39,
    CHAR_WARP_BLOCK = 40,
    CHAR_PLUNDER_CHEST = 41,
    CHAR_BOWSER_PHONE = 42,
    CHAR_DUELING_GLOVE = 43,
    CHAR_LUCKY_LAMP = 44,
    CHAR_GOLDEN_MUSHROOM = 45,
    CHAR_BOO_BELL = 46,
    CHAR_BOO_REPELLENT = 47,
    CHAR_BOWSER_SUIT = 48,
    CHAR_MAGIC_LAMP = 49,
    CHAR_ITEM_BAG = 50,
    CHAR_KOOPA_KARD = 51,
    CHAR_BARTER_BOX = 52,
    CHAR_GAME_GUY_COIN = 53,
    CHAR_WACKY_WATCH = 54,
    CHAR_MR_BLIZZARD_GIANT = 55,
    CHAR_SKELETON_KEY_2 = 56,
    CHAR_ANGLER_FISH = 57,
    CHAR_BLOOPER = 58,
    CHAR_SUSHI = 59,
    CHAR_JEANIE = 60,
    CHAR_MONTY_MOLE = 61,
    CHAR_WOODY = 62,
    CHAR_WARUKIO = 63
};

enum REV_FLAGS {
    FLAG_REV = 1,
    FLAG_UNK_80 = 0x80
};

enum PlayerFlags {
    PLAYER_IS_CPU = 1,
};

#endif //_ENUMS_H_